Posix sh : remove bashism from build.sh (#19)
* be compatible with POSIX shell

avoid bashism

* fix error !

* fix strip

* mintlib needs more than POSIX shell anyway :(

error: The syntax $(<file) is unsupported by /bin/sh.
       Please use "make SHELL=/bin/bash" instead.

* remove == bashism

* one last fix... forgot something

* fix "midnight" builds

I had the issue of make trying to make the  mintlib-CVS-20170106 after midnight :

CVSROOT=:pserver:cvsanon:cvsanon@sparemint.org:/mint cvs checkout -d mintlib-CVS-20170107 mintlib
cvs checkout: Updating mintlib-CVS-20170107
U mintlib-CVS-20170107/.cvsignore
[...]
U mintlib-CVS-20170107/unix/write.c
cd mintlib-CVS-20170106 && patch -p1 < ../mintlib.patch
/bin/sh: line 0: cd: mintlib-CVS-20170106: No such file or directory
make: *** [mintlib-CVS-20170106] Error 1